seed_everything: 42
trainer:
  accelerator: cpu
  accumulate_grad_batches: 1
  barebones: null
  benchmark: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 7
        mode: "min"
  detect_anomaly: false
  deterministic: null
  check_val_every_n_epoch: 1
  default_root_dir: null
  devices: 1
  enable_checkpointing: true
  fast_dev_run: false
  gradient_clip_algorithm: null
  gradient_clip_val: null
  limit_train_batches: null
  limit_test_batches: null
  limit_val_batches: null
  log_every_n_steps: 50
  logger: true
  max_epochs: 500
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  enable_progress_bar: true
  reload_dataloaders_every_n_epochs: 0
  use_distributed_sampler: null
  strategy: auto
  sync_batchnorm: false
  val_check_interval: null
  enable_model_summary: false
  inference_mode: true
model:
  num_target_classes: 50
  lr: 0.0001
  lr_scheduler_gamma: 0.1
  num_workers: 12
  model_path: data/BEATs/BEATs_iter3_plus_AS2M.pt
data:
  root_dir: data/ESC-50-master/audio/
  csv_file: data/ESC-50-master/meta/esc50.csv
  batch_size: 1
  transform: null
finetuning:
  milestones: 0
ckpt_path: null